/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "stm32f446.h"
#include "GPIO.h"

void delayMillis(uint16_t delay);		//delay function
int main(void)
{
	GPIO_Handle_t rectangle;
	rectangle.pGPIOx = GPIOA;
	rectangle.GPIO_PinConfig.GPIO_PinNumber 		= GPIO_PIN0;
	rectangle.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_OUT;
	rectangle.GPIO_PinConfig.GPIO_PinSpeed 			= GPIO_SPEED_FAST;
	rectangle.GPIO_PinConfig.GPIO_PinOPType 		= GPIO_OPTYPE_PP;
	rectangle.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;

	//Clock activate for GPIOA AHB1ENR
	GPIO_PCLK(GPIOA,ENABLE);
	//GPIO Init
	GPIO_Init(&rectangle);
	while(1)
	{
		//GPIO_Write(GPIOA, GPIO_PIN0, Value);
		GPIO_Write(&rectangle, GPIO_PIN_SET);
		delayMillis(500);
		GPIO_Write(&rectangle, GPIO_PIN_RESET);
		delayMillis(500);
	}
}

void delayMillis(uint16_t delay)
{
	uint16_t i = 0;
	for(;delay>0; --delay)
	{
		for(i = 0; i<1245;++i)
		{
			;
		}
	}
}

